<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>10.0.2</Version>
    <AssemblyVersion>10.0.2.0</AssemblyVersion>
    <FileVersion>10.0.2.0</FileVersion>
    <InformationalVersion>10.0.2</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SetupFlavor)' == 'MediaPlayer'">
    <DefineConstants>$(DefineConstants);NINGRAN_MEDIA_PLAYER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NingRan.Core.Tests" />
  </ItemGroup>

</Project>
