<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <StartupHookSupport>false</StartupHookSupport>
    <EnableDiagnostics>false</EnableDiagnostics>
  </PropertyGroup>
</Project>
