namespace NingRan.Windows;

/// <summary>
/// English labels declared directly in XAML. The shared window loader uses
/// this table so dialogs keep the selected language consistently.
/// </summary>
internal static class EnglishUiSupplement
{
    public static readonly IReadOnlyDictionary<string, string> Text =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["安全交付"] = "Secure Delivery", ["第 1 步，共 5 步：选择资料"] = "Step 1 of 5: Choose content",
            ["选择要交给对方的文件和文件夹"] = "Choose files and folders to send", ["添加文件"] = "Add files", ["添加文件夹"] = "Add folder", ["移除所选"] = "Remove selected", ["尚未选择资料。"] = "No content selected.",
            ["填写交付信息"] = "Enter delivery details", ["交付名称"] = "Delivery name", ["交付说明（可不填）"] = "Delivery note (optional)", ["接收对象（可不指定）"] = "Recipient (optional)",
            ["只有已经完成安全码核对的联系人会出现在这里；不指定联系人时不会显示成“已确认接收方”。"] = "Only contacts whose security code has been verified appear here. Without a contact, the recipient is not marked as confirmed.",
            ["设置保护方式"] = "Set protection", ["交付密码"] = "Delivery password", ["再次输入"] = "Confirm password", ["建议使用至少 16 个字符、容易记住但别人猜不到的口令。"] = "Use a memorable passphrase of at least 16 characters that others cannot guess.",
            ["发送者身份"] = "Sender identity", ["发送者身份密码"] = "Sender identity password", ["更多保护方式"] = "More protection options", ["只使用交付密码（推荐）"] = "Delivery password only (recommended)", ["交付密码＋密匙文件"] = "Delivery password + key file", ["交付密码＋物理设备"] = "Delivery password + physical device", ["交付密码＋Windows Hello"] = "Delivery password + Windows Hello", ["选择密匙"] = "Choose key",
            ["生成时需要逐一出示所选设备；接收方打开时需使用其中一个设备。"] = "Every selected device is required when creating the package; the recipient needs one of them to open it.", ["登记本机 Windows Hello"] = "Register Windows Hello on this computer", ["只能在登记的本机和当前 Windows 账户使用；请保留交付密码作为恢复方式。"] = "This works only on the registered computer and current Windows account. Keep the delivery password as a recovery method.",
            ["设置使用规则"] = "Set usage rules", ["有效期"] = "Expiration", ["1 天"] = "1 day", ["7 天"] = "7 days", ["30 天（推荐）"] = "30 days (recommended)", ["90 天"] = "90 days", ["永久有效"] = "No expiration", ["允许接收方导出明文文件"] = "Allow the recipient to export plaintext files", ["请了解离线限制"] = "Understand offline limitations",
            ["有效期依赖接收方电脑的本地时间。离线软件无法完全阻止手动修改系统时间。禁止导出也无法阻止截图、拍照或录屏。"] = "Expiration depends on the recipient computer's local time. Offline software cannot fully prevent manual clock changes. Disabling export cannot prevent screenshots, photos, or recording.", ["检查并生成"] = "Review and create", ["保存位置"] = "Save location", ["选择"] = "Choose", ["安全交付包已生成并通过自动检查"] = "Secure Delivery package created and verified", ["打开保存位置"] = "Open save location", ["复制接收说明"] = "Copy recipient instructions", ["上一步"] = "Back", ["取消"] = "Cancel", ["下一步"] = "Next",
            ["导出加密包（.nrenc）"] = "Export encrypted package (.nrenc)", ["导出明文"] = "Export plaintext", ["导出内容"] = "Export content", ["还原普通文件或文件夹。导出后请自行保护该位置的明文内容。"] = "Restore ordinary files or folders. Protect the exported plaintext location yourself.", ["可复制到任意磁盘或发送给他人；内容继续保持加密，不会生成明文。"] = "Copy it to any disk or share it. The content stays encrypted and no plaintext is created.", ["请选择本次导出的内容类型"] = "Choose what to export", ["继续"] = "Continue",
            ["输入密码"] = "Enter password", ["请输入密码"] = "Enter password", ["加密包保护方式"] = "Archive protection", ["密码＋密匙文件"] = "Password + key file", ["密码＋物理设备"] = "Password + physical device", ["密匙文件"] = "Key file", ["密码、密匙、设备、Hello"] = "Password, key, device, or Hello", ["密码＋设备"] = "Password + device", ["高级模式"] = "Advanced", ["选择加密文件后只显示必要的公开信息。"] = "Only necessary public information is shown after selecting an encrypted file.", ["请输入加密时使用的密码。"] = "Enter the password used during encryption.",
            ["请选择左侧文件"] = "Select a file on the left", ["全部媒体"] = "All media", ["视频"] = "Video", ["音频"] = "Audio", ["文本"] = "Text", ["文件列表"] = "File list", ["程序内部安全播放"] = "Secure in-app playback", ["程序内部安全浏览"] = "Secure in-app browsing", ["保险箱安全媒体查看"] = "Secure vault media view", ["保险箱内部浏览"] = "Browse inside vault", ["暂停"] = "Pause", ["播放或暂停"] = "Play or pause", ["播放结束后"] = "After playback", ["播完停止"] = "Stop after playback", ["自动下一项"] = "Play next", ["循环当前项"] = "Repeat item", ["循环整个列表"] = "Repeat list", ["音量"] = "Volume", ["缩放"] = "Zoom", ["全屏"] = "Full screen", ["凝然安全媒体查看"] = "NingRan secure media view", ["凝然加密 · 安全媒体播放器"] = "NingRan Encryption · Secure media player", ["不保存明文"] = "No plaintext saved", ["不保存明文，文件只在内存中按需读取"] = "No plaintext is saved; data is read on demand in memory",
            ["选择需要保护或还原的内容"] = "Choose content to protect or restore", ["支持单个文件或整个文件夹，大于 10 GB 也可以正常处理。"] = "Single files and folders are supported, including files larger than 10 GB.", ["把文件或文件夹拖到这里"] = "Drop a file or folder here", ["也可以点击下方按钮选择"] = "Or choose one with a button below", ["批量加密"] = "Batch encryption", ["分片加密（生成 .nrsplit 文件）"] = "Split encryption (creates .nrsplit files)", ["每片最大大小"] = "Maximum part size", ["搜索已解锁内容的文件名"] = "Search unlocked content by name", ["完整检查"] = "Full check", ["导出记录"] = "Export history", ["历史记录"] = "History", ["大文件会边加密边写入多个分片；把所有分片放在同一目录，双击任意一个即可进入安全查看。"] = "Large files are encrypted into parts while writing. Keep all parts in one folder and double-click any part to open secure view.",
            ["使用默认程序打开"] = "Open with the default program", ["选择媒体文件的打开方式"] = "Choose how media files open", ["选择音频和视频的打开方式"] = "Choose how media opens", ["选择加密文件和安全交付包中内容的打开方式。"] = "Choose how content in encrypted files and Secure Delivery packages opens.", ["使用单独安装的凝然播放器查看音频、视频、图片和 PDF。未安装或连接失败时会提示并停止，不会改用其他查看方式。"] = "Use the separately installed NingRan Player for audio, video, images, and PDF. If it is missing or cannot connect, NingRan shows an error and stops without switching routes.", ["使用单独安装的凝然播放器查看音频、视频、图片和 PDF。未安装或连接失败时，会自动改用内置查看器。"] = "Use the separately installed NingRan Player for audio, video, images, and PDF. If it is missing or cannot connect, NingRan shows an error and stops without switching routes.", ["直接在凝然加密窗口中查看或播放音频、视频、图片和 PDF。"] = "View or play audio, video, images, and PDF directly inside NingRan Encryption.",
            ["保险箱"] = "Vault", ["创建保险箱"] = "Create a vault", ["打开保险箱"] = "Open a vault", ["创建并打开保险箱"] = "Create and open vault", ["内部浏览"] = "Browse inside", ["创建、打开和管理可读写保险箱"] = "Create, open, and manage writable vaults", ["选择这次要做的事情。创建和打开使用各自独立的界面。"] = "Choose what you want to do. Creating and opening use separate interfaces.", ["设置保存位置、容量和密码，也可以建立使用第二套密码的独立空间。"] = "Set a location, capacity, and password, with an optional independent space opened by a second password.", ["选择已有保险箱，输入对应密码，然后挂载为临时磁盘并自动打开。"] = "Choose an existing vault, enter its password, then mount it as a temporary drive and open it automatically.", ["开始创建"] = "Start creating", ["开始打开"] = "Start opening", ["挂载失败时才会提供软件内查看作为备用方式。"] = "In-app browsing is offered only as a fallback if mounting fails.",
            ["保险箱位置"] = "Vault location", ["保险箱名称"] = "Vault name", ["保险箱密码"] = "Vault password", ["固定总容量"] = "Fixed capacity", ["建立隐蔽空间"] = "Create a private space", ["秘密密码"] = "Private-space password", ["秘密密码与空间容量"] = "Private-space password and capacity", ["日常空间容量（GB）"] = "Everyday-space capacity (GB)", ["隐蔽空间容量（GB）"] = "Private-space capacity (GB)", ["挂载并打开"] = "Mount and open", ["锁定并卸载磁盘"] = "Lock and remove drive", ["添加文件…"] = "Add files...", ["添加文件夹…"] = "Add folder...", ["删除"] = "Delete", ["替换文件内容"] = "Replace contents", ["移动或重命名"] = "Move or rename", ["新建文件夹"] = "New folder", ["安全查看"] = "Secure view", ["导出明文…"] = "Export plaintext...", ["选择文件后点击“安全查看”。"] = "Select a file, then choose Secure view.", ["请选择要操作的内容。"] = "Select an item to work with.", ["取消当前操作"] = "Cancel operation",
            ["后退"] = "Back", ["前进"] = "Forward", ["上一级"] = "Up", ["搜索当前文件夹"] = "Search this folder", ["快速访问"] = "Quick access", ["此电脑"] = "This PC", ["名称"] = "Name", ["修改日期"] = "Date modified", ["类型"] = "Type", ["大小"] = "Size", ["尚未选择文件"] = "No files selected", ["普通单击只选择一项；按住 Shift 单击可增加选择。"] = "Click to select one item; Shift-click to add another.", ["追加所选文件"] = "Append selected files", ["文件夹"] = "File folder", ["文件"] = "File", ["自动改名"] = "Rename automatically", ["替换"] = "Replace", ["跳过"] = "Skip", ["全部自动改名"] = "Rename all automatically", ["全部替换"] = "Replace all", ["全部跳过"] = "Skip all", ["取消整个追加操作"] = "Cancel entire append", ["⇩  下载"] = "⇩  Downloads", ["⌂  主文件夹"] = "⌂  Home", ["▣  桌面"] = "▣  Desktop", ["▤  文档"] = "▤  Documents", ["▧  图片"] = "▧  Pictures",
            ["选择要追加的文件"] = "Choose files to append", ["物理设备管理"] = "Physical device management", ["登记 U 盘/移动硬盘"] = "Register USB/removable drive", ["登记 FIDO2 安全密钥"] = "Register FIDO2 security key", ["从清单移除"] = "Remove from list", ["完成"] = "Done", ["设备名称"] = "Device name", ["给这台设备起一个容易辨认的名称"] = "Give this device an easy-to-recognize name", ["例如：老大的随身 U 盘、办公室备用密钥"] = "For example: Travel USB drive or office backup key",
            ["4 GB（推荐）"] = "4 GB (recommended)", ["把一组资料按有效期和导出规则安全交给别人"] = "Securely send a set of content with expiry and export rules", ["必须插入的密匙（从已选择密匙中指定）"] = "Required devices (choose from selected devices)", ["打开最近安全查看过的加密文件"] = "Open recently viewed encrypted files", ["禁止插入的已登记移动存储（插入任意一把都会拒绝解锁）"] = "Forbidden registered removable devices (any one refuses unlock)", ["外接物理密匙"] = "External physical device", ["物理密匙的新规则会在下一步界面设置必需名单、至少需要数量和禁止插入名单；当前版本要求使用可持续检测的移动存储密匙。"] = "The next step sets required devices, the minimum count, and forbidden devices. The current version requires a continuously detectable removable device.", ["自定义解锁条件（勾选的条件必须全部满足）"] = "Custom unlock conditions (every checked condition is required)", ["自定义组合"] = "Custom combination", ["组合中至少需要插入几把"] = "Minimum number of devices", ["Windows Hello 只能在登记的本机和当前 Windows 账户解锁；请保留密码或密匙文件作为恢复方式。"] = "Windows Hello unlocks only on the registered computer and Windows account. Keep a password or key file as recovery.",
            ["最近生成的安全交付"] = "Recently created Secure Delivery", ["安全交付"] = "Secure Delivery", ["请先等待当前操作结束，再创建安全交付包。"] = "Wait for the current operation to finish before creating a Secure Delivery package.",
            ["帮助文档"] = "Help", ["打开使用说明、隐私条件和免责声明"] = "Open usage instructions, privacy terms, and disclaimer", ["按功能查找详细说明、操作步骤和安全边界。"] = "Find detailed instructions, workflows, and safety boundaries by feature.", ["按功能名称、按钮或关键词搜索"] = "Search by feature, button, or keyword", ["点击功能名称查看详细说明。"] = "Select a feature to read its complete guide.", ["搜索"] = "Search", ["凝然加密帮助文档"] = "NingRan Encryption Help",
        };
}
