<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>NingRan.StrictMonitor</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>6.1.16</Version>
    <AssemblyVersion>6.1.16.0</AssemblyVersion>
    <FileVersion>6.1.16.0</FileVersion>
    <InformationalVersion>6.1.16</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
</PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\NativeElevationBinding.cs" Link="NativeElevationBinding.cs" />
  </ItemGroup>
</Project>
